version: "3.3"
services:
   container_name: simple
    build:
      context: ./react-production
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - .:/app
    depends_on:
      - server
    restart: always
    networks:
      - example-net
