@@ -1,15 +1,52 @@
@@ -0,0 +1,14 @@
# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'

version: 2.1

orbs:
  node: circleci/node@4.1
  docker: circleci/docker@1.6.0

jobs:
   build:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run test
